; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	; esphome/AsyncTCP@^3.3.2
    esp32async/ESPAsyncWebServer@3.10.2
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit BME280 Library@^2.3.0

lib_ignore =
  ESPAsyncTCP          ; (ESP8266)
  RPAsyncTCP           ; (RP2040/Mbed) while compiling for ESP32, these libraries are not needed and can cause conflicts, so we ignore them
  AsyncTCP_RP2040
  AsyncTCP_Generic